# Generated by Django 5.0 on 2023-12-29 16:59

import prasath.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=prasath.models.getFileName
                    ),
                ),
                ("description", models.TextField(max_length=500)),
            ],
        ),
    ]
